### ISSUE TITLE
Question: Usage without redux

### ISSUE THREAD

**Issue by panta82** [LogRocket/redux-logger#245]
I use redux-logger with redux and that's great. But I also have a several services outside of redux. I'd like to use the same logger there as well.

Sure, I could just console.log it, but then I lose all the configuration, colors and safety checking that went into this code.

Do you have some suggestion on how I can use this logger outside of redux? Maybe just getting the kernel of the logger out of the redux harness? Or simulating actions with a wrapper?

I'll try a few patterns anyway, I was just wondering if there was an "official" way of doing this.

**Comment by evgenyrodionov** [comment]
Hi!

What exactly do you need and expect from that logger? Can you show example?

**Comment by panta82** [comment]
The parts of redux logger I'd like to have in other services are:
- shared logging level
- timestamp
- colors
- the same visual format (event type, followed by bolded event name, followed by timestamp, and then collapsed details)
- maybe automatic duration measurement (a notion of "start" and "end" event)
 
So, I imagine an API where I could extract out of `redux-logger` as a simple function, with the same config as the middleware.

```javascript
const logger = createLogger(ENV.logger);
middleware.push(logger.middleware); // <-- no longer middleware by default

apiClient.setLogger(logger); // inject logger into different services
```

Then I could use it like this.

```javascript
logger('api request', 'http://mysite.com/api/path/to/url', {
  body: {/*..*/},
  token: '...'
});
```
I would see a grayed out "api request", followed by bold url, and the request body would be collapsed.

Of course, this is just one way you could do an API like this. Maybe another (better?) way would be to have a generic javascript logger as a separate module, and have redux-logger wrap around it.

I didn't look too deeply into the redux-logger code, I don't know how/if anything like this is feasible.

**Comment by pshev** [comment]
I think @panta82 has a great point.
I just wanted to write a logger for a different state management library. It also uses the idea of event-sourcing for state-management but has no concept of middleware. I really hoped I could use all the great work done here. Unfortunately I couldn't and had to copy-paste a bunch :(

The basic problem is that `redux-logger` is tied to the idea of being a redux-middleware when most of it's functionality has no relation to it.

Any system that uses events (actions) and wants to log them along with some state before and after the event occurred could benefit from using the functionality that is inside `redux-logger`.
I does sound like we need some `generic-event-logger` module to achieve that.

@evgenyrodionov do you think that make some sense?

**Comment by grushetsky** [comment]
@panta82, frankly, it seems like what you actually need is an enhanced `console` module (like [loglevel](https://github.com/pimterry/loglevel) or [Console++](https://github.com/detro/consoleplusplus)).

@pshev, the support for other state management libraries is not one of the current goals of `redux-logger`. It really is a middleware tailored for Redux (thus, comes the package name 🙂). But you can surely abstract away some of the approaches used in `redux-logger`.
