### ISSUE TITLE
undefined action logged when using await

### ISSUE THREAD

**Issue by clutter-tech** [LogRocket/redux-logger#290]
I have an action like this:
```
export const loadResource = (id) => async (dispatch, _, { axios }) => {
  const response = await axios.get(`/resources/${id}.json`);
  // ...
};
```
The first line in the function results in the following being logged:
```
action undefined @ 10:10:01.060
redux-logger.js:1  prev state {blah: {...}}
redux-logger.js:1  action     ƒ (_x4, _x5, _x6) {
      return _ref4.apply(this, arguments);
    }
redux-logger.js:1  next state {blah: {...}}
```
Can `redux-logger` avoid logging the undefined action like the above? It is any `await` that causes this, i.e. `await new Promise((r) => setTimeout(() => r(console.log("Hi")), 1000))`

**Comment by evgenyrodionov** [comment]
Can you make a demo on codesandbox.io? Thanks

**Comment by grushetsky** [comment]
@clutter-tech, are you sure that you pass the correct action object as you dispatch an action (there's no `dispatch` call in the example above)? A demo would be helpful.

**Comment by NevenLeung** [comment]
@evgenyrodionov , @grushetsky , when to publish a new release? It seems to fixed by vvitto.


This problem occurrs in an async action with [redux-thunk](https://github.com/reduxjs/redux-thunk). In the READEME.md of redux-thunk, it uses `Promise` to make async actions.


When dispatching an async action with `Promise`, redux-logger will log the function detail of async action creator, because it doesn't return an object with `type` field.


The code using `Promise` can be implemented with `async/await`, just like the following code.

```js
import { db, removeDoc, getDocsByType } from '../api/pouchdb.js';

const REMOVE_ARTICLE_REQUEST = 'app/articles/REMOVE_ARTICLE_REQUEST';

const removeArticleRequest = () => (
  {
    type: REMOVE_ARTICLE_REQUEST
  }
);

const REMOVE_ARTICLE_SUCCESS = 'app/articles/REMOVE_ARTICLE_SUCCESS';

const removeArticleSuccess = (articles) => (
  {
    type: REMOVE_ARTICLE_SUCCESS,
    articles
  }
);

const REMOVE_ARTICLE_FAILURE = 'app/articles/REMOVE_ARTICLE_FAILURE';

const removeArticleFailure = (error) => (
  {
    type: REMOVE_ARTICLE_FAILURE,
    error
  }
);

// async action implemented with Promise

// function removeArticle(id) {
//   return function (dispatch) {
//     dispatch(removeArticleRequest());
//    
//     return removeDoc(db, 'article_' + id)
//       .then(...)
//       ...
//   }
// }

const removeArticle = (id) => async (dispatch) => {
  dispatch(removeArticleRequest());

  let res = undefined;

  try {
    await removeDoc(db, 'article_' + id);
    res = await getDocsByType(db, 'article');

    if (typeof res === "object" && 'docs' in res && res.docs.length !== 0) {
      dispatch(removeArticleSuccess(res.docs));
    } else {
      dispatch(removeArticleFailure('It is failed to remove article_' + id));
    }
  } catch (error) {
    dispatch(removeArticleFailure(error));
  }

  return res;
};

// To call the async action with redux-thunk.
// store.dispatch(removeArticle(id));
```

When dispatching an async action with `async/await`, redux-logger will only log the info  like this.

```
action undefined 
| prev state > Object
| action       ƒ (_x) {
|                return _ref.apply(this, arguments);
|              }
| next state > Object

action REMOVE_ARTICLE_REQUEST
| prev state > Object
| action     > Object 
| next state > Object
```

Both async action in `Promise` or `async/await`, redux-logger will log the function info after compiled by **Babel**, and `undefined` as action type.

#### Solution in my opion

When dispatch an async action which doesn't return an object containing a `type` field, using the function name of action creator as action type may make sense.

**Comment by evgenyrodionov** [comment]
Still waiting for demo on codesandbox

**Comment by NevenLeung** [comment]
I have already known why the proble occurred. Just as #20 said.

The demo is here,  

[![Edit Redux Example - Async Fetch Photo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ovqmvy4wo6)

```js
// ./src/store/configStore.js

import { applyMiddleware, createStore } from "redux";
import { composeWithDevTools } from "redux-devtools-extension";

// import middleware
import logger from "redux-logger";
import thunk from "redux-thunk";

// import reducer
import reducer from "../reducers";

function configureStore(preLoadedState) {
  // middleware
  const middleware = [thunk, logger];

  const middlewareEnhancer = applyMiddleware(...middleware);

  const enhancers = [middlewareEnhancer];

  const composedEnhancers = composeWithDevTools(...enhancers);

  return createStore(reducer, preLoadedState, composedEnhancers);
}

export default configureStore;
```

In the code, `const middleware = [logger, thunk];`, when the `logger` is not the last place in the middleware chain, it will cause the problem like what I mention before.

But after I put the `logger` at the last place, like `const middleware = [thunk, logger];`, everything works well.

I think this issue can be closed.
