### ISSUE TITLE
New machine, fresh install of our React / Redux project, lost output for filenames + line numbers?

### ISSUE THREAD

**Issue by daveschumaker** [LogRocket/redux-logger#297]
Recently upgraded to a new machine at work and am going through the process of setting everything up. After cloning our project from Git using MacOS High Sierra (v10.13.4), I no longer get the correct output for filenames and line numbers when actions are dispatched.

Every action points to 'redux-logger.js?a125:1' instead of the file name it was dispatched from. Other devs who've previously setup the project, using the same `package.json` file and pulling the same versions of npm libraries as I are able to see the correct output in their console.

![screen shot 2018-05-15 at 11 29 32 am](https://user-images.githubusercontent.com/5395723/40077042-54626896-5835-11e8-81cc-d5264acfa561.png)

![screen shot 2018-05-15 at 11 30 14 am](https://user-images.githubusercontent.com/5395723/40077053-59451232-5835-11e8-9f3d-ca35e6f1fe12.png)

Any ideas what might be happening or anything additional info I can provide? Thanks!

```
node v8.10.0
npm v5.6.0
```

**Comment by ashishdhyani** [comment]
I am facing the similar issue, redux-logger has stopped displaying the file names

Instead of displaying actual file names, it displays something like this "blob:http://<server>/4eefbb4d89bc:20376"

Chrome version: 64.0.3282.119

`
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-promise": "^0.5.3",
    "redux-thunk": "^2.2.0",
`

`	import thunk from 'redux-thunk';
	import promise from 'redux-promise';
	import {createLogger} from 'redux-logger';
	import allReducers from './reducers';
	
	const logger = createLogger();
	const store = createStore(
		allReducers,
		applyMiddleware(thunk, promise, logger)
	);
`

**Comment by eranimo** [comment]
This doesn't appear to happen anymore in Chrome 72 with the latest version. Please let me know if you have it happen again, and I will investigate.
