### ISSUE TITLE
Can no longer expand object within VS Code Debug Console

### ISSUE THREAD

**Issue by maplion** [LogRocket/redux-logger#303]
I am not sure what relates to what yet or what is truly at fault, but in the process of upgrading from Angular 5.2.6 => 6.0.4, my redux-logger, which still functions outside of debug mode (i.e. reading it from Chrome console), no longer works properly when debugging in Visual Studio Code.  The output is there, but I can no longer expand any of the objects (the arrow goes down, but nothing is rendered).  I can go back to my previous Angular 5 project and it works fine [note: redux and redux-logger versions are the same: 3.7.2 and 3.0.6 respectively]; that being said, a lot of other things were upgraded (but I would expect it not to function at all if it were having issues).  Has anyone else experienced this and/or has a solution as the primary place I use the logger is in debug mode since it won't let me inspect the browser console when in debug mode?

**Comment by eranimo** [comment]
I believe the problem is that VSCode is filtering out `console.info` by default here, but the groups remain visible but appear to be empty since their contents are being filtered out. It looks like you can change the settings in VSCode to change this.

**Comment by maplion** [comment]
> I believe the problem is that VSCode is filtering out `console.info` by default here, but the groups remain visible but appear to be empty since their contents are being filtered out. It looks like you can change the settings in VSCode to change this.

Hi @eranimo Thanks for the insight, is it possible for you to elaborate on what setting might cause this?
