### ISSUE TITLE
Log only errors

### ISSUE THREAD

**Issue by izmn** [LogRocket/redux-logger#305]
I want to log only errors, how can I configure that?

I tried solution suggested by @evgenyrodionov, but it does not work
```js
const logger = createLogger({
  level: {
    prevState: false,
    action: false,
    nextState: false,
    error: `error`,
  }
});
```

Installed version: "redux-logger": "^3.0.6",

ref https://github.com/evgenyrodionov/redux-logger/issues/145

**Comment by evgenyrodionov** [comment]
What you mean by “it doesn’t work”?

**Comment by izmn** [comment]
I mean, even with this config it still shows all redux logs,
but I want to hide all logs except errors

**Comment by evgenyrodionov** [comment]
Cab you please make a demo on codesandbox.io
