### ISSUE TITLE
Is there a way to limits logs to only the client or the server? (for universal apps)

### ISSUE THREAD

**Issue by mherodev** [LogRocket/redux-logger#306]
Redux logs are a bit noisy on the server, it'd be nice to limit them only to the client by default in our app.

**Comment by fatlinesofcode** [comment]
using next.js
```
const logger = createLogger({
    collapsed:true,
    predicate:(getState, action) => {
      return process.browser
    }
  });
```

**Comment by mherodev** [comment]
I'll give this a shot! Thanks @fatlinesofcode

**Comment by mherodev** [comment]
That did it (finally got around to implementing this, thanks again!)
