### ISSUE TITLE
Logs can't be expanded in Chrome and Chromium

### ISSUE THREAD

**Issue by boristian** [LogRocket/redux-logger#330]
Hello,
thank you for your awesome work.
Lately i'm having a problem with the logs in the Chrome and Chromium browser console.
In Chrome 79.0.3945.117 and Chromium 81.0.4021.0 logs can't be expanded. The icon points to the right direction (right for collapsed and down for expanded) but there is no data shown. In Firefox 72.0.1 everything works fine. I am using redux-logger v3.0.6.

![Screenshot](https://user-images.githubusercontent.com/5909013/72352150-073a6e00-36e2-11ea-9ca2-6ac412a9876f.png)

**Comment by eranimo** [comment]
Do you have the log filter open? If you're filtering for a type other than `info` then the groups won't be expanded. This is because Chrome doesn't filter out groups when they have no filtered children.

**Comment by boristian** [comment]
Thank you for your response and sorry for your time.
Somehow i managed to set the filter in both browsers to 'errors' and so nothing but errors are expanded 🙈 
Everything works fine and i will close this issue.
